
result = {'has_more': True,
 'next_cursor': 'b49a43fc-b31c-4dc8-bec0-8433fd74cf09',
 'object': 'list',
 'results': [{'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '2d77345a-4121-40ff-a84f-0d8f1db7c441',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 10000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 10000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'orange',
                                                       'id': 'd77720e2-53b5-424c-b403-6063cd341de4',
                                                       'name': '황현'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 10000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/2d77345a412140ffa84f0d8f1db7c441'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '3d4320c6-42ac-4b81-b75b-c44db5033ddc',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 10000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 10000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'orange',
                                                       'id': '225ba168-70ad-46bd-88cd-fe688610d5a1',
                                                       'name': '전재문'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 10000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/3d4320c642ac4b81b75bc44db5033ddc'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '4395f5ad-9037-474f-8688-3b9dcbe97b84',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 5000,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 5000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 0, 'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'gray',
                                                       'id': 'd022748b-a39e-4b56-8fb4-fa4a486c1a29',
                                                       'name': '박광서'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '입금방식': {'id': 'bD}L',
                                      'select': {'color': 'default',
                                                 'id': 'l@Ve',
                                                 'name': '계좌이체'},
                                      'type': 'select'},
                             '주일헌금': {'formula': {'number': 5000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/4395f5ad9037474f86883b9dcbe97b84'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '553d72b2-0f0d-4fba-9f34-e95c80182916',
              'last_edited_time': '2021-12-05T09:49:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 11000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 11000,
                                                'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 11000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'yellow',
                                                       'id': '43536532-25fd-4745-ad8b-1e1a33b0a012',
                                                       'name': '주일학교'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'default',
                                               'id': '53c46769-ea54-4856-8fd8-7d490667925e',
                                               'name': '주일학교'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/553d72b20f0d4fba9f34e95c80182916'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '7b3de7ac-974d-4f33-949c-4bcd7f6b3e76',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 50000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 50000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'green',
                                                       'id': 'a0a5e59b-30e7-42f3-a4ac-5a0949e44ad7',
                                                       'name': '무명'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 50000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/7b3de7ac974d4f33949c4bcd7f6b3e76'}]}
{'and': [{'property': '날짜', 'text': {'is_not_empty': True}}]}
{'has_more': True,
 'next_cursor': 'b49a43fc-b31c-4dc8-bec0-8433fd74cf09',
 'object': 'list',
 'results': [{'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '2d77345a-4121-40ff-a84f-0d8f1db7c441',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 10000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 10000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'orange',
                                                       'id': 'd77720e2-53b5-424c-b403-6063cd341de4',
                                                       'name': '황현'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 10000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/2d77345a412140ffa84f0d8f1db7c441'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '3d4320c6-42ac-4b81-b75b-c44db5033ddc',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 10000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 10000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'orange',
                                                       'id': '225ba168-70ad-46bd-88cd-fe688610d5a1',
                                                       'name': '전재문'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 10000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/3d4320c642ac4b81b75bc44db5033ddc'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '4395f5ad-9037-474f-8688-3b9dcbe97b84',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 5000,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 5000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 0, 'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'gray',
                                                       'id': 'd022748b-a39e-4b56-8fb4-fa4a486c1a29',
                                                       'name': '박광서'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '입금방식': {'id': 'bD}L',
                                      'select': {'color': 'default',
                                                 'id': 'l@Ve',
                                                 'name': '계좌이체'},
                                      'type': 'select'},
                             '주일헌금': {'formula': {'number': 5000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/4395f5ad9037474f86883b9dcbe97b84'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '553d72b2-0f0d-4fba-9f34-e95c80182916',
              'last_edited_time': '2021-12-05T09:49:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 11000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 11000,
                                                'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 11000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'yellow',
                                                       'id': '43536532-25fd-4745-ad8b-1e1a33b0a012',
                                                       'name': '주일학교'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'default',
                                               'id': '53c46769-ea54-4856-8fd8-7d490667925e',
                                               'name': '주일학교'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/553d72b20f0d4fba9f34e95c80182916'},
             {'archived': False,
              'cover': None,
              'created_time': '2021-12-05T09:42:00.000Z',
              'icon': None,
              'id': '7b3de7ac-974d-4f33-949c-4bcd7f6b3e76',
              'last_edited_time': '2021-12-05T09:45:00.000Z',
              'object': 'page',
              'parent': {'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19',
                         'type': 'database_id'},
              'properties': {'COMMENT': {'id': 'wvcJ',
                                         'rich_text': [],
                                         'type': 'rich_text'},
                             '감사헌금': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '~qyD',
                                      'type': 'formula'},
                             '계좌이체': {'formula': {'number': 0,
                                                  'type': 'number'},
                                      'id': '_ZRd',
                                      'type': 'formula'},
                             '금액': {'id': 'dPiL',
                                    'number': 50000,
                                    'type': 'number'},
                             '기타': {'formula': {'number': 0, 'type': 'number'},
                                    'id': 'R`BD',
                                    'type': 'formula'},
                             '날짜': {'id': 'CYeJ',
                                    'rich_text': [{'annotations': {'bold': False,
                                                                   'code': False,
                                                                   'color': 'default',
                                                                   'italic': False,
                                                                   'strikethrough': False,
                                                                   'underline': False},
                                                   'href': None,
                                                   'plain_text': '2021-11-21',
                                                   'text': {'content': '2021-11-21',
                                                            'link': None},
                                                   'type': 'text'}],
                                    'type': 'rich_text'},
                             '봉헌': {'formula': {'number': 50000,
                                                'type': 'number'},
                                    'id': '@ukf',
                                    'type': 'formula'},
                             '봉헌자': {'id': 'nKjI',
                                     'multi_select': [{'color': 'green',
                                                       'id': 'a0a5e59b-30e7-42f3-a4ac-5a0949e44ad7',
                                                       'name': '무명'}],
                                     'type': 'multi_select'},
                             '십일조': {'formula': {'number': 0, 'type': 'number'},
                                     'id': 'mQ;x',
                                     'type': 'formula'},
                             '열': {'id': 'zRw;',
                                   'rich_text': [],
                                   'type': 'rich_text'},
                             '주일헌금': {'formula': {'number': 50000,
                                                  'type': 'number'},
                                      'id': 'J<LG',
                                      'type': 'formula'},
                             '특이사항': {'id': 'title',
                                      'title': [],
                                      'type': 'title'},
                             '항목': {'id': 'K`fe',
                                    'select': {'color': 'yellow',
                                               'id': 'f8b7277c-723d-4d57-a577-70beec0bfce0',
                                               'name': '주일헌금'},
                                    'type': 'select'}},
              'url': 'https://www.notion.so/7b3de7ac974d4f33949c4bcd7f6b3e76'}]}


from pprint import pprint

# print(result.keys())



class QueriedPageIterator:

    def __init__(self, request, result_data):
        self._request = request

        self.object = result_data['object']
        self.results = result_data['results']
        self.next_cursor = result_data['next_cursor']
        self.has_more = result_data['has_more']

        self.results_iter = iter(self.results)

        print(self.object,
         self.next_cursor,
         self.has_more)

    def __iter__(self):
        self.results_iter = iter(self.results)
        return self

    def __next__(self):
        try:
            return next(self.results_iter)
        except StopIteration:

            if self.has_more:
                print('has more')
                raise StopIteration
            else:
                print('None Result')
                raise StopIteration



def pdir(obj, level='public'):
    attr_list = dir(obj)
    if level == 'hide':
        attr_list = [a for a in attr_list if a[:2] != '__']
    elif level == 'public':
        attr_list = [a for a in attr_list if a[0] != '_']
    return attr_list


def dev1():

    import notion_api.notion
    from pprint import pprint
    from notion_api.query import filter
    import time
    notion = notion_api.notion.Notion('secret_rvDkx9qH8AVG3aKBVwZ4r5Byo75uoAPMrQ1I6bo4d6G')
    # d3 = notion.get_database('6c3409803b7643b9b818b78765b69c82')
    # d3 = notion.get_database('f7001a895f39403eae3d90b6451639f4')  # test2
    d3 = notion.get_database('44d6b8fda2734f04968a771a79f97fb6') # test1
    # d4 = notion.get_database('f7001a895f39403eae3d90b6451639f4')  # test1

    # p = notion.get_page('e8d28d7c0056414582fe23f2ab7c3928')

    # print(d3, pdir(d3), d3.parent)
    print(d3.properties)
    d3.title = '테스트2'
    # title = p.properties['Title']
    # print(title)
    # title.title = 'TitleFixed1'

    # p.properties['Checkbox'] = False
    # ckbox = p.properties['Checkbox']
    # ckbox.ckbox = False
    # print()
    # ckbox.checkbox = False

# a = {'object': 'page', 'id': '3560dfbd-a86a-4252-8875-a9578a5dab8a', 'created_time': '2021-07-11T16:04:00.000Z', 'last_edited_time': '2021-07-11T16:04:00.000Z', 'cover': None, 'icon': None, 'parent': {'type': 'database_id', 'database_id': '989cc0ed-5d16-4c6b-b7fe-852e51fb8e19'}, 'archived': False, 'properties': {'봉헌': {'id': '@ukf', 'type': 'formula', 'formula': {'type': 'number', 'number': 30000}}, '날짜': {'id': 'CYeJ', 'type': 'rich_text', 'rich_text': [{'type': 'text', 'text': {'content': '2021-07-11', 'link': None}, 'annotations': {'bold': False, 'italic': False, 'strikethrough': False, 'underline': False, 'code': False, 'color': 'default'}, 'plain_text': '2021-07-11', 'href': None}]}, '주일헌금': {'id': 'J<LG', 'type': 'formula', 'formula': {'type': 'number', 'number': 0}}, '항목': {'id': 'K`fe', 'type': 'select', 'select': {'id': 'ef9dadfb-d40e-48ce-a34d-ccbf29ea821b', 'name': '감사헌금', 'color': 'default'}}, '기타': {'id': 'R`BD', 'type': 'formula', 'formula': {'type': 'number', 'number': 0}}, '계좌이체': {'id': '_ZRd', 'type': 'formula', 'formula': {'type': 'number', 'number': 0}}, '금액': {'id': 'dPiL', 'type': 'number', 'number': 30000}, '십일조': {'id': 'mQ;x', 'type': 'formula', 'formula': {'type': 'number', 'number': 0}}, '봉헌자': {'id': 'nKjI', 'type': 'multi_select', 'multi_select': [{'id': 'f116e11b-c6a5-4ed6-a25d-8a2468d7ea84', 'name': '김선교', 'color': 'blue'}, {'id': '0ea01575-a6b5-4caf-9c1d-8bb24789d8a6', 'name': '김일환', 'color': 'red'}]}, 'COMMENT': {'id': 'wvcJ', 'type': 'rich_text', 'rich_text': []}, '열': {'id': 'zRw;', 'type': 'rich_text', 'rich_text': []}, '감사헌금': {'id': '~qyD', 'type': 'formula', 'formula': {'type': 'number', 'number': 30000}}, '특이사항': {'id': 'title', 'type': 'title', 'title': []}}, 'url': 'https://www.notion.so/3560dfbda86a42528875a9578a5dab8a'}


# pprint(a)

if __name__ == '__main__':
    dev1()